#!/bin/bash
# Name:             BASH Framework Date Library
# Creator:          James Seiters
# Creation Date:    2022-07-22
# Modifier:
# Modified Date:
# Description:      Functions for working with dates.

##### Parameters #####

##### Script Variables #####

##### Framework Functions #####
## Echos the last day of the month.
## Inputs: An integer representing the month
## Outputs: An interger representing the day.
## Notes: for m in {1..12}; do   date -d "$m/1 + 1 month - 1 day" "+%b - %d days";  done
last_day_of_month {
  # Parameters:
  #  1 - month to find last day of
  date --date "$1/1 + 1 month - 1 day" +%d
}

##### Script Functions #####
in_array {
  # 1- first date string, 2 - second date string, 3 - units to return
  first_date=$1
  second_date=$2
  unit=$3

  local value=$1
  local tests=$2

  tests=(year month week day hour minute second)

  old_IFS=$IFS
  IFS="|"

  if [[ ! $( printf "$IFS${tests[*]}$IFS" ) =~ "$IFS$unit$IFS" ]]; then
    # TODO Add error handling

  fi

  IFS=$old_IFS
}

##### Process Options #####

##### Main #####
